# Generated by Django 6.0.4 on 2026-04-30 20:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('draft_type', models.CharField(choices=[('CLAIM_PETITION', 'Claim Petition u/s 166 MV Act'), ('LEGAL_NOTICE', 'Legal Notice'), ('AFFIDAVIT', 'Affidavit'), ('COMPENSATION', 'Statement of Compensation'), ('WRITTEN_ARGS', 'Written Arguments'), ('VAKALATNAMA', 'Vakalatnama'), ('REPLY', 'Reply / Written Statement'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('content', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Under Review'), ('FINAL', 'Final'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_prompt', models.TextField(blank=True)),
                ('ref_no', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='cases.case')),
            ],
            options={
                'verbose_name': 'Draft',
                'verbose_name_plural': 'Drafts',
                'ordering': ['-version', '-created_at'],
            },
        ),
    ]
