# Generated by Django 6.0.4 on 2026-05-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='draft_type',
            field=models.CharField(choices=[('CLAIM_PETITION', 'Claim Petition u/s 166 MV Act'), ('LEGAL_NOTICE', 'Legal Notice'), ('AFFIDAVIT', 'Affidavit'), ('COMPENSATION', 'Statement of Compensation'), ('WRITTEN_ARGS', 'Written Arguments'), ('VAKALATNAMA', 'Vakalatnama'), ('REPLY', 'Reply / Written Statement'), ('DEMAND_LETTER', 'Demand Letter to Insurance Company'), ('SETTLEMENT', 'Settlement Letter'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
