# Generated by Django 6.0.4 on 2026-04-30 20:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('case_no', models.CharField(blank=True, max_length=100)),
                ('case_type', models.CharField(choices=[('MACT', 'Motor Accident Claims (MACT)'), ('PROPERTY', 'Property Dispute'), ('CRIMINAL', 'Criminal'), ('CIVIL', 'Civil'), ('CONSUMER', 'Consumer'), ('LABOUR', 'Labour / Employment'), ('FAMILY', 'Family / Matrimonial'), ('OTHER', 'Other')], default='MACT', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('CLOSED', 'Closed'), ('STAYED', 'Stayed')], default='ACTIVE', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('client_name', models.CharField(max_length=255)),
                ('client_age', models.CharField(blank=True, max_length=20)),
                ('client_address', models.TextField(blank=True)),
                ('father_name', models.CharField(blank=True, max_length=255)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('accident_date', models.DateField(blank=True, null=True)),
                ('accident_place', models.CharField(blank=True, max_length=255)),
                ('vehicle_no', models.CharField(blank=True, max_length=50)),
                ('fir_no', models.CharField(blank=True, max_length=100)),
                ('hospital', models.CharField(blank=True, max_length=255)),
                ('tribunal', models.CharField(blank=True, max_length=255)),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('injuries', models.JSONField(blank=True, default=list)),
                ('compensation', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
