# Generated by Django 6.0.4 on 2026-04-30 20:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injuries', models.JSONField(default=list)),
                ('treatments', models.JSONField(default=list)),
                ('medications', models.JSONField(default=list)),
                ('icd_codes', models.JSONField(default=list)),
                ('economic_damages', models.JSONField(default=dict)),
                ('non_economic_damages', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('ai_raw_output', models.TextField(blank=True)),
                ('missing_docs', models.JSONField(default=list)),
                ('case_strength', models.CharField(blank=True, max_length=20)),
                ('legal_strategy', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_summary', to='cases.case')),
            ],
            options={
                'verbose_name': 'Medical Summary',
                'verbose_name_plural': 'Medical Summaries',
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('doctor', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('tag', models.CharField(choices=[('EMERGENCY', 'Emergency'), ('SPECIALIST', 'Specialist Consult'), ('CHIROPRACTIC', 'Chiropractic'), ('SURGERY', 'Surgery'), ('FOLLOW_UP', 'Follow Up'), ('DISCHARGE', 'Discharge'), ('PHYSIOTHERAPY', 'Physiotherapy'), ('INVESTIGATION', 'Investigation / Scan'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('medications', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='cases.case')),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'ordering': ['date', 'order'],
            },
        ),
    ]
