# Generated by Django 5.2.10 on 2026-09-29 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='source_coordinates',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_timeline_events', to='documents.document'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='source_page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='source_snippet',
            field=models.TextField(blank=True),
        ),
    ]
