# Generated by Django 6.0.4 on 2026-04-30 20:25

import apps.documents.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('doc_type', models.CharField(choices=[('CASE_FILE', 'Case File'), ('MEDICAL', 'Medical Record'), ('FIR', 'FIR / Police Report'), ('INSURANCE', 'Insurance Document'), ('COURT_ORDER', 'Court Order / Judgment'), ('EVIDENCE', 'Evidence'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('pages', models.PositiveIntegerField(default=0)),
                ('extracted_text', models.TextField(blank=True)),
                ('page_texts', models.JSONField(default=list)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('processing_error', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
