# Generated by Django 5.2.10 on 2026-10-01 10:48

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='supabase_path',
            field=models.CharField(blank=True, help_text='Path in Supabase bucket', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='supabase_url',
            field=models.URLField(blank=True, help_text='Supabase Storage URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.documents.models.document_upload_path),
        ),
    ]
